version: '3'
services:
  app:
    build: .
    ports:
      - "3030:3030"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://ma90@db:54321/contacts
  db:
    image: postgres:16
    ports:
      - "54321:54321"
    environment:
      - POSTGRES_USER=ma90
      - POSTGRES_DB=contacts